# Generated by Django 5.2.8 on 2025-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_founditem_image_lostitem_image_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbs/'),
        ),
    ]
