# Generated by Django 5.2.8 on 2025-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_founditem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbs/'),
        ),
    ]
