# Generated by Django 5.2.8 on 2025-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_lostitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='successstory',
            name='item_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
