# Generated by Django 5.2.8 on 2025-12-11 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0005_successstory_image_url_successstory_item_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AddField(
            model_name='founditem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='allow_featured',
            field=models.BooleanField(default=False, verbose_name='Allow to be featured'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='successstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('keys', 'Keys & Access'), ('wallets', 'Wallets & Purses'), ('documents', 'Documents'), ('jewelry', 'Jewelry & Accessories'), ('clothing', 'Clothing'), ('bags', 'Bags & Luggage'), ('pets', 'Pets'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='item_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
