# Generated by Django 5.2.8 on 2025-12-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0006_alter_successstory_options_founditem_claimed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='thumbnail',
        ),
    ]
